"""Synthesising media from hazards we actually found.

This is the simulation half of the system. The detection pipeline mines public
traffic cameras for real road-hazard edge cases; this port turns one of those
detections into a dashcam-perspective clip that an AV perception stack could
train on. Rare events are exactly what such stacks are short of, and exactly
what a fleet of traffic cameras sees all day.

**Nothing here is evidence.** Everything this port produces is generated, and
the whole module is built so that fact cannot get lost:

* Clips carry `synthetic=True` and the name of the model that made them.
* Keys are namespaced under `SYNTHETIC_PREFIX`, in a directory separate from the
  real frames, so no code walking the evidence store can pick one up.
* Nothing here is reachable from the filing path. A report to a DOT contains
  real stills from a public camera or it contains nothing.

That separation is the point rather than a precaution: a hazard report backed by
generated footage would be a fabricated record, and the value of this project
rests on its reports being auditable.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from pydantic import BaseModel, Field

from road_cleaner.domain.models import utcnow

# Every generated artifact lives under this prefix. `is_synthetic_key` is the
# check the web layer and the retention sweep both use.
SYNTHETIC_PREFIX = "synthetic/"


class MediaUnavailableError(RuntimeError):
    """The media model could not be reached, timed out, or refused the prompt.

    Raised rather than swallowed, matching `VisionUnavailableError`. A missing
    clip is a missing clip; it must not quietly resolve to a real frame.
    """


class SyntheticClip(BaseModel):
    """One generated artifact plus the provenance needed to label it honestly.

    `seeded_from_frame_id` is what makes this defensible as training data rather
    than invention: it points back at the real detection the scenario came from,
    so any clip can be traced to the camera frame that prompted it.
    """

    key: str
    mime_type: str
    model_name: str
    prompt: str
    seeded_from_frame_id: str | None = None
    seeded_from_case_id: str | None = None
    duration_seconds: float | None = None
    size_bytes: int = 0
    created_at: datetime = Field(default_factory=utcnow)
    # Not configurable, and not a default that callers may override. Anything
    # this port returns was generated by a model.
    synthetic: bool = True

    @property
    def label(self) -> str:
        """The badge text. Rendered anywhere a clip is shown."""
        return f"SYNTHETIC — generated by {self.model_name}"


def is_synthetic_key(key: str) -> bool:
    """Whether a blob key belongs to generated media rather than camera evidence."""
    return key.startswith(SYNTHETIC_PREFIX)


@runtime_checkable
class VideoSynthesizer(Protocol):
    """Renders a road-hazard scenario as video.

    Two implementations: Veo on Vertex AI, and a scripted one that replays clips
    already cached on disk so the dashboard and tests run with no credentials
    and no spend.
    """

    @property
    def model_name(self) -> str: ...

    async def render_scenario(
        self,
        *,
        prompt: str,
        seed_image: bytes | None = None,
        duration_seconds: int = 8,
        frame_id: str | None = None,
        case_id: str | None = None,
    ) -> SyntheticClip:
        """Generate one clip and store it.

        `seed_image` is the real evidence frame the scenario is built from --
        image-to-video keeps the generated scene anchored to the road that was
        actually photographed, instead of an unrelated invented one.

        Raises `MediaUnavailableError` if the model is unreachable, the operation
        times out, or safety filtering rejects the prompt.
        """
        ...


@runtime_checkable
class SpeechSynthesizer(Protocol):
    """Reads a dispatch briefing aloud. Chirp 3 HD, or a scripted no-op."""

    @property
    def model_name(self) -> str: ...

    async def narrate(self, text: str, *, case_id: str | None = None) -> SyntheticClip: ...


@runtime_checkable
class MusicSynthesizer(Protocol):
    """Scores the demo reel. Lyria, or a scripted no-op.

    Worth being clear about scope: Lyria generates instrumental music. It does
    not produce sound effects -- sirens, tyre noise, impacts. Veo's own
    `generate_audio` is what produces diegetic sound for a clip.
    """

    @property
    def model_name(self) -> str: ...

    async def score(self, prompt: str, *, name: str = "reel") -> SyntheticClip: ...
