"""Turning domain objects into things a template can render.

All the presentation that deliberately does *not* live in the domain -- colours,
percentages, formatted timestamps, CSS positions -- is computed here. That way
changing how a case looks never means touching a model or migrating a table.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from road_cleaner.domain.enums import (
    CASE_KIND_LABELS,
    CHANNEL_LABELS,
    STAGE_LABELS,
    STATE_LABELS,
    CaseKind,
    Tone,
)
from road_cleaner.domain.models import Case, CaseWithDetail, Detection, FrameRef, Incident
from road_cleaner.domain.sla import elapsed_fraction, format_remaining, rationale_for
from road_cleaner.ports.media import SYNTHETIC_PREFIX

# Matches the TONE map in the design comps.
TONE_COLORS: dict[str, str] = {
    "filed": "#2F7A4F",
    "escalated": "#B4451F",
    "watching": "#8A6A10",
    "cleared": "#6B6B65",
    "suppressed": "#9A9A92",
}

# The SLA bar shifts colour as a case runs out of time.
SLA_COLORS = {
    "ok": "#0F5340",
    "close": "#F2C230",
    "over": "#E2622B",
    "closed": "#4A7A5E",
    "none": "#74776E",
}

FILTERS: list[dict[str, str]] = [
    {"key": "all", "label": "All"},
    {"key": "filed", "label": "Filed"},
    {"key": "watching", "label": "Watching"},
    {"key": "escalated", "label": "Past due"},
    {"key": "cleared", "label": "Cleared"},
]

STATES: list[dict[str, str]] = [
    {"key": "all", "label": "All states"},
    {"key": "GA", "label": "Georgia"},
    {"key": "FL", "label": "Florida"},
    {"key": "NC", "label": "N. Carolina"},
]


def tone(case: Case) -> str:
    return TONE_COLORS.get(case.kind.value, "#6B6B65")


def when(moment: datetime | None) -> str:
    """Short stamp used in the log, e.g. 'Mon 14:02'."""
    return moment.strftime("%a %H:%M") if moment else "—"


def frame_url(ref: FrameRef | None) -> str | None:
    if ref is None or not ref.blob_key:
        return None
    return f"/frames/{ref.blob_key}"


_MEDIA_KINDS = {
    ".mp4": ("video", "video/mp4"),
    ".webm": ("video", "video/webm"),
    ".mp3": ("audio", "audio/mpeg"),
    ".wav": ("audio", "audio/wav"),
}


def media_for_case(media_root: Path | None, case_id: str) -> list[dict[str, Any]]:
    """Generated clips and audio for one case, newest first.

    Reads the filesystem rather than the database on purpose. Synthetic media is
    deliberately not modelled as part of a Case -- it is not evidence, it has no
    place in the audit trail, and nothing in the filing path should be able to
    reach it by following a foreign key. A directory listing keeps that boundary
    where it is.
    """
    if media_root is None:
        return []
    folder = Path(media_root) / SYNTHETIC_PREFIX / case_id
    if not folder.is_dir():
        return []

    items = []
    for path in sorted(folder.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True):
        kind_mime = _MEDIA_KINDS.get(path.suffix.lower())
        if kind_mime is None:
            continue
        kind, mime = kind_mime
        # The model name comes from the provenance sidecar the adapter wrote.
        # Only fall back to the filename if it is missing -- guessing produced
        # captions like "generated by briefing" for a Chirp voice.
        model = _model_from_manifest(path) or path.stem.rsplit("-", 1)[-1]
        items.append(
            {
                "kind": kind,
                "mime": mime,
                "url": f"/media/{SYNTHETIC_PREFIX}{case_id}/{path.name}",
                "model": model,
                "size_mb": f"{path.stat().st_size / 1_000_000:.1f}",
                # Rendered as a badge everywhere this appears. Not optional.
                "badge": f"SYNTHETIC — generated by {model}",
                # Same claim, fewer characters, for the library cards where the
                # full sentence wraps onto two lines and reads as clutter. It
                # still names the model -- that is the part that must survive.
                "badge_short": f"SYNTHETIC — {model}",
            }
        )
    return items


def _model_from_manifest(path: Path) -> str | None:
    sidecar = path.with_name(path.name + ".json")
    if not sidecar.is_file():
        return None
    try:
        return json.loads(sidecar.read_text()).get("model_name") or None
    except (ValueError, OSError):
        return None


# The scenario library's own vocabulary. Deliberately not the analyst's hazard
# enum verbatim -- a library of training data is browsed by what is *in* the
# clip, not by the incident taxonomy the report was filed under.
HAZARD_LABELS: dict[str, str] = {
    "debris": "Debris",
    "flooding": "Flooding",
    "stalled_vehicle": "Stalled vehicle",
    "animal": "Animal",
    "infrastructure_damage": "Damaged infrastructure",
    "unreported_closure": "Unmarked closure",
    "pedestrian_on_highway": "Pedestrian",
}


def _road_type(camera) -> str:
    """Road character, matching the language the Veo prompts are built from."""
    road = ((camera.road if camera else "") or "").upper()
    if road.startswith("I-"):
        return "Interstate"
    if road.startswith(("US-", "SR-", "GA-", "FL-", "NC-")):
        return "State route"
    return "Highway"


def _lighting(moment: datetime | None) -> str:
    """Time-of-day band, derived from when the hazard was actually seen.

    Only the hour is real, so only the hour is claimed. The comps showed weather
    ("Overcast, midday") but nothing in the pipeline records weather, and a
    library of training data whose metadata is invented is worth nothing.
    """
    if moment is None:
        return ""
    hour = moment.hour
    if hour < 5:
        return "Night"
    if hour < 8:
        return "Dawn"
    if hour < 11:
        return "Morning"
    if hour < 15:
        return "Midday"
    if hour < 19:
        return "Afternoon"
    if hour < 22:
        return "Dusk"
    return "Night"


def scenario_card(
    case: Case, media_root: Path | None, camera=None, refused: bool = False
) -> dict[str, Any]:
    """One card in the scenario library.

    Three states, and the card renders differently for each:

    * ``refused``  -- a hazard we will not simulate. No clip, and no button to
      make one. Shown rather than hidden, because the refusal is a feature.
    * ``clip``     -- generated media exists.
    * ``generate`` -- a real confirmed case with no clip yet.
    """
    media = media_for_case(media_root, case.id)
    videos = [m for m in media if m["kind"] == "video"]
    hazard_key = getattr(case.hazard_type, "value", str(case.hazard_type))

    if refused:
        state = "refused"
    elif videos:
        state = "clip"
    else:
        state = "generate"

    meta = [
        HAZARD_LABELS.get(hazard_key, hazard_key.replace("_", " ").title()),
        _road_type(camera),
        _lighting(case.opened_at),
    ]
    return {
        "id": case.id,
        "state": state,
        "title": case.hazard_title,
        "hazard_key": hazard_key,
        "hazard_label": HAZARD_LABELS.get(hazard_key, hazard_key),
        "meta": " · ".join(p for p in meta if p),
        "location": case.location,
        "case_url": f"/cases/{case.id}",
        "clip": videos[0] if videos else None,
        "frame_url": frame_url(evidence_frame(case)),
    }


def mode_for(case_id: str) -> str:
    """Which of the two endings this case demonstrates: 'auto' or 'assisted'.

    The division is presentational, and deliberately so. Every case in the
    library has a clip, which means every one of them *could* be run either way
    -- the two modes differ in who ends up holding the report, not in what the
    pipeline is capable of. Two sections exist so both answers are visible at
    once rather than hidden behind a toggle somebody has to find.

    The tempting alternative was to split on something real: agencies that
    publish an inbox can be written to automatically, agencies that publish only
    a web form cannot. That is the honest distinction and it is why the second
    mode exists at all -- but in the seeded data it lands 1 case against 10,
    which shows a visitor one example of the interesting half and ten of the
    other.

    Derived from the case id rather than from a position in a list, because two
    different pages have to agree about it. Index parity over the *filtered*
    library reshuffled the whole split every time somebody clicked a hazard
    chip, and left the case page with no way to work out which ending its own
    case belonged to.

    `sha256` rather than `hash()`, which is salted per process: the same case
    would land in a different section after a restart, and on Cloud Run after
    every deploy.
    """
    digest = hashlib.sha256(case_id.encode()).digest()
    return "auto" if digest[0] % 2 == 0 else "assisted"


def split_by_mode(
    cards: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """The library, divided into the two sections. See `mode_for`."""
    automatic = [c for c in cards if mode_for(c["id"]) == "auto"]
    assisted = [c for c in cards if mode_for(c["id"]) == "assisted"]
    return automatic, assisted


def scenario_filters(cards: list[dict[str, Any]], active: str) -> list[dict[str, Any]]:
    """Hazard chips with real counts. Only hazards actually present get a chip."""
    counts: dict[str, int] = {}
    labels: dict[str, str] = {}
    for card in cards:
        key = card["hazard_key"]
        counts[key] = counts.get(key, 0) + 1
        labels[key] = card["hazard_label"]

    chips = [
        {
            "key": "all",
            "label": "All hazards",
            "count": len(cards),
            "href": "/?hazard=all",
            "active": active == "all",
        }
    ]
    chips.extend(
        {
            "key": key,
            "label": labels[key],
            "count": counts[key],
            "href": f"/?hazard={key}",
            "active": active == key,
        }
        for key in sorted(counts, key=lambda k: (-counts[k], labels[k]))
    )
    return chips


def library_summary(cards: list[dict[str, Any]]) -> str:
    """The line beside the heading. Counts what exists, never rounds up."""
    clips = sum(1 for c in cards if c["state"] == "clip")
    return (
        f"{clips} of {len(cards)} scenarios · 16:9 · 1920×1080 · "
        "seeded from confirmed cases"
    )


def box_style(case: Case) -> str | None:
    """Position the detection overlay from the model's own fractions."""
    if case.box is None:
        return None
    b = case.box
    return (
        f"left:{b.x * 100:.1f}%;top:{b.y * 100:.1f}%;"
        f"width:{b.width * 100:.1f}%;height:{b.height * 100:.1f}%"
    )


def _recomposed_report(
    analysis: dict[str, Any], detail: CaseWithDetail, settings: Any
) -> dict[str, Any] | None:
    """The report text rebuilt from live facts, or None to keep what was cached.

    The detection comes from the sidecar rather than from `detail.detections`,
    which looks like the obvious source and is the wrong one: outside a real
    sweep those rows are the scripted seeds, so composing from them would trade
    the sentence Gemini actually wrote for a fixture. What the model saw belongs
    to the run; where it is and who owns it belong to the record.

    Returns None rather than a half-built report whenever the sidecar predates a
    field or holds a value the current enums do not know. A stale body is worse
    than a fresh one and better than a broken one.
    """
    from road_cleaner.domain import narrative
    from road_cleaner.domain.enums import HazardType, Severity

    if not analysis.get("report_body"):
        return None  # nothing was composed, so there is nothing to re-say
    found = [f for f in (analysis.get("frames") or []) if f.get("found")]
    if not found:
        return None

    # The frame the evidence still was cut from, so the picture and the words
    # describe the same moment. Falls back to the last frame that saw anything.
    at = analysis.get("evidence_at")
    frame = next((f for f in found if f.get("at") == at), found[-1])

    try:
        # `.astimezone()` because parsing an ISO string yields a fixed offset,
        # which `observed_at` renders as "UTC-07:00" where a live run -- whose
        # datetime came from `now().astimezone()` -- renders "PDT". Same instant
        # either way; this keeps a recomposed report and a fresh one identical.
        when = datetime.fromisoformat(analysis["analyzed_at"]).astimezone()
        detection = Detection(
            camera_id=detail.case.camera_id,
            frame_id=str(frame.get("index", "")),
            analyzed_at=when,
            hazard_type=HazardType(frame["hazard"]),
            lane_position=frame.get("lane") or "unknown",
            severity=Severity(frame["severity"]),
            confidence=float(frame["confidence"]),
            description=frame["description"],
        )
    except (KeyError, TypeError, ValueError):
        return None

    # A site-relative path is useless in somebody's inbox; PUBLIC_BASE_URL is
    # what makes it openable. Same rule as `Inspector._public`: a whole URL or
    # no URL, never half of one.
    base = (getattr(settings, "public_base_url", "") or "").rstrip("/")
    still = analysis.get("evidence_url")
    return {
        "report_subject": narrative.report_subject(
            detection,
            detail.camera.road if detail.camera else detail.case.location,
            tier=1,
        ),
        "report_body": narrative.report_body(
            detection,
            detail.case.location,
            narrative.observed_at(when),
            attachment_count=0,
            evidence_url=f"{base}{still}" if base and still else None,
            tier=1,
        ),
    }


def last_analysis(
    media_root: Path | str | None,
    case_id: str,
    detail: CaseWithDetail | None = None,
    settings: Any = None,
) -> dict[str, Any] | None:
    """The most recent run of the agent over this case's clip, if there was one.

    Read from the sidecar beside the clip rather than from the database, for the
    same reason `media_for_case` reads the filesystem: an analysis of generated
    footage is not part of the case record and must not be reachable by
    following a foreign key out of one.

    Lets the page open showing a real boxed still and the last verdict, instead
    of an empty frame and a button. Whatever it shows is labelled with when it
    ran -- it is a previous result, not a live one, and the two are not
    interchangeable.
    """
    if media_root is None:
        return None
    from road_cleaner.pipeline.inspect import cached_analysis, clip_for_case

    clip = clip_for_case(media_root, case_id)
    if clip is None:
        return None
    analysis = cached_analysis(clip)
    if analysis is None:
        return None

    # The cache outlives the files it points at -- media is pruned, and keys
    # have changed shape before now. An `<img>` at a 404 renders as a broken
    # icon where the evidence should be, which reads as the detection having
    # failed rather than the picture having moved.
    url = analysis.get("evidence_url")
    if url and not (Path(media_root) / url.removeprefix("/media/")).is_file():
        analysis = {**analysis, "evidence_url": None, "evidence_at": None}

    # The wording is derived too, from two things that move independently: what
    # the model saw, which is in this sidecar and is the real Gemini output, and
    # where the case is, which lives on the record and changes the moment
    # somebody drops a pin. Recomposing from both costs no Vertex call and is
    # what stops a cached body insisting stills are attached -- nothing has
    # enclosed one since `attachment_count` went to 0, and `mailto:` could not
    # carry it even if something did.
    #
    # Done before the block below, which feeds this text into the form payload.
    if detail is not None:
        rewritten = _recomposed_report(analysis, detail, settings)
        if rewritten is not None:
            analysis = {**analysis, **rewritten}

    # Where a report goes is a property of the agency, not of the run that
    # happened to compose it -- so it is recomputed every time rather than read
    # back from the sidecar. Caches written before the Send button existed have
    # no destination at all, and caches written before the registry moved from
    # placeholder endpoints to the DOTs' real forms have a stale one. Both are
    # wrong in the same way: the answer belongs to the registry.
    if detail is not None and detail.agency:
        from road_cleaner.pipeline.inspect import destination_for

        destination, channel, payload = destination_for(
            detail.case,
            detail.agency,
            settings,
            subject=analysis.get("report_subject") or "",
            body=analysis.get("report_body") or "",
        )
        analysis = {
            **analysis,
            # The agency's *name*, for the same reason as its endpoint. The
            # sidecar records who owned the road when the run happened, and
            # moving a case re-runs the jurisdiction lookup and rewrites
            # `case.agency_id` -- so a page reading the cached name showed the
            # old DOT next to the new DOT's form. Both halves of that came from
            # this block; only one of them was being refreshed.
            "agency": detail.agency.name,
            "report_destination": destination,
            "report_channel": channel,
            "report_email": detail.agency.email or None,
            # Recomputed too: the fields are built from the endpoint and the
            # report text, so a stale payload would name a stale destination.
            "report_payload": payload,
        }
    return analysis


def box_caption(case: Case, detection: Detection | None = None) -> str:
    """The caption on the overlay: what it is, and how sure we were.

    Derived, never read from `cases.box_label`. That column is written once at
    open and then drifts -- NC-1169 stores 0.77 against a case confidence of
    0.91 -- so a page rendering it shows a number contradicted by the rest of
    the same page. The detection is the better source when we have it; the case
    is at least self-consistent when we do not.
    """
    src = detection or case
    return f"{src.hazard_type.value.replace('_', ' ')} · {src.confidence:.2f}"


def evidence_frame(case: Case) -> FrameRef | None:
    """The frame that best represents the case: cleared shot, else key evidence."""
    clear = next((f for f in case.frame_refs if f.clear and f.blob_key), None)
    if case.kind is CaseKind.CLEARED and clear:
        return clear
    marked = next((f for f in case.frame_refs if f.mark and f.blob_key), None)
    return marked or next((f for f in case.frame_refs if f.blob_key), None)


def case_row(case: Case) -> dict[str, Any]:
    """One row in the road log."""
    frame = evidence_frame(case)
    return {
        "id": case.id,
        "kind": case.kind.value,
        "status": CASE_KIND_LABELS.get(case.kind.value, case.kind.value),
        "tone": tone(case),
        "hazard": case.hazard_title,
        "location": case.location,
        "when": when(case.opened_at),
        "sentence": case.sentence,
        "ref_label": case.ref_label or "NOTHING SENT",
        "ref": case.reference or f"held · {case.confidence:.2f}",
        "frame_url": frame_url(frame),
        "box_style": box_style(case),
        "box_label": box_caption(case),
        "box_clear": bool(frame and frame.clear),
        "suppressed": case.kind is CaseKind.SUPPRESSED,
    }


def sla_view(case: Case, now: datetime) -> dict[str, Any]:
    """The time-remaining bar."""
    if case.closed_at is not None and case.kind is CaseKind.CLEARED:
        return {
            "note": case.ref_label or "closed",
            "color": SLA_COLORS["closed"],
            "pct": 100,
            "why": "Confirmed clear against the original evidence frame.",
        }
    if case.sla_deadline is None:
        return {
            "note": "no filing",
            "color": SLA_COLORS["none"],
            "pct": 0,
            "why": (
                "Nothing was sent, so no clock is running. This stays under "
                "observation until it clears or crosses the bar to report."
            ),
        }

    remaining = format_remaining(case.sla_deadline, now)
    fraction = elapsed_fraction(case.opened_at, case.sla_deadline, now)
    if remaining.endswith("overdue"):
        color = SLA_COLORS["over"]
    elif fraction > 0.75:
        color = SLA_COLORS["close"]
    else:
        color = SLA_COLORS["ok"]
    return {
        "note": remaining,
        "color": color,
        "pct": round(fraction * 100),
        "why": rationale_for(case.hazard_type),
    }


def case_detail(detail: CaseWithDetail, now: datetime) -> dict[str, Any]:
    """Everything the case page renders."""
    case = detail.case
    watching = case.kind in (CaseKind.WATCHING, CaseKind.FILED, CaseKind.ESCALATED)

    frames = [
        {
            "label": f.label,
            "time": f.captured_at.strftime("%H:%M:%S") if f.captured_at else "—",
            "url": frame_url(f),
            "mark": f.mark,
            "clear": f.clear,
        }
        for f in case.frame_refs
    ]

    # Whether anything actually left the building. Everything the report card
    # claims is conditioned on this.
    dry_run = all(f.dry_run for f in detail.filings) if detail.filings else True
    # The detection that *opened* the case. Not `detections[-1]`: an Auditor
    # re-check appended later is a clearance question, not evidence about who
    # found the hazard, and reading the last one made six of eleven pages
    # disown a genuine Gemini detection as "scripted".
    opening = detail.detections[0] if detail.detections else None
    model_name = opening.model_name if opening else "scripted"

    return {
        "case": case,
        "state_code": case.state_code,
        "number": case.number,
        "status": CASE_KIND_LABELS.get(case.kind.value, case.kind.value),
        "tone": tone(case),
        "watching": watching,
        "camera_label": detail.camera.label if detail.camera else case.camera_id,
        "road": (
            f"{detail.camera.road} {detail.camera.direction or ''}".strip().upper()
            if detail.camera
            else ""
        ),
        "county": detail.camera.county if detail.camera else None,
        # Where the pin sits when the page opens. The map is a correction tool,
        # so it starts on the answer the case already has rather than empty.
        "lat": detail.camera.lat if detail.camera else None,
        "lng": detail.camera.lng if detail.camera else None,
        "live_frame": frame_url(evidence_frame(case)),
        "box_style": box_style(case),
        "box_label": box_caption(case, opening),
        "frames": frames,
        "trail": [
            {
                "time": t.at.strftime("%a %H:%M:%S"),
                "text": t.text,
                "tone": t.tone.value,
                "stage": STAGE_LABELS.get(t.stage.value, t.stage.value),
            }
            for t in detail.trail
        ],
        # Two things were visible only inside the trail block, and the trail
        # block is gone: a filing that failed and is being retried, and the
        # decision to stop escalating and hand a case to a person. Both are
        # things a reader needs to know without opening anything.
        "attention": next(
            (t.text for t in reversed(detail.trail) if t.tone is Tone.WARN), None
        ),
        "agency": detail.agency.name if detail.agency else None,
        # In dry run the report was composed and never transmitted, so the past
        # tense is a lie. The distinction has to survive into the API too, not
        # just the template -- `/api/cases/{id}` is documented surface.
        "channel_label": "How it would go out" if dry_run else "How it went out",
        "channel": (
            CHANNEL_LABELS.get(case.channel.value, case.channel.value)
            if case.channel
            else "Nothing sent"
        ),
        "reference": case.reference or "—",
        # The reference is minted locally by `synthesize_reference`, which hashes
        # the case id into the agency's own format. It looks exactly like a real
        # NCDOT or GDOT number and it is not one -- no agency has ever seen this
        # case. Saying so beside it is the difference between a demo and a
        # fabricated record.
        "reference_is_placeholder": dry_run and bool(case.reference),
        "ref_label": case.ref_label or "NOTHING SENT",
        "sla": sla_view(case, now),
        "letter": detail.filings[-1].body if detail.filings else None,
        "letter_subject": detail.filings[-1].subject if detail.filings else None,
        "was_dry_run": dry_run,
        "filing_count": len(detail.filings),
        "last_checked": when(case.last_checked_at),
        "model_json": case.raw_model_json,
        "model_name": model_name,
        # Whether a vision model actually looked at this, or whether the
        # detection was replayed from `seeds/scenarios.json` by the scripted
        # analyzer. The narrative reads identically either way -- it is generated
        # from the detection by `narrative.explain` -- so without this the page
        # presents canned demo data in exactly the voice of a real model call.
        #
        # Derived from the detection rather than from configuration, so it stays
        # correct per case: a database can hold scripted cases from a demo run
        # and real ones from a live run side by side.
        "is_scripted": model_name == "scripted",
        "explain": case.explain,
    }


def summary_line(counts: dict[str, int]) -> str:
    """The mono line under the heading, e.g. '11 cases · 4 filed · 2 cleared'."""
    total = sum(counts.values())
    if not total:
        return "no cases yet"
    parts = [f"{total} case{'s' if total != 1 else ''}"]
    for kind in ("filed", "cleared", "escalated", "watching"):
        if counts.get(kind):
            parts.append(f"{counts[kind]} {CASE_KIND_LABELS[kind].lower()}")
    if counts.get("suppressed"):
        parts.append(f"{counts['suppressed']} stood down")
    return " · ".join(parts)


def stat_band(stats: dict[str, Any]) -> list[dict[str, str]]:
    """The headline numbers, each labelled with what it actually counts.

    Two of these used to be labelled as something they were not:

    * **"the official feed never saw"** reads as a comparison against a state
      511 feed. It is not. It is `filed / (filed + suppressed)` — the gate's own
      file-vs-suppress ratio, which also counts duplicates and correlations. A
      good number under a claim it does not support is worse than no number.
    * **"reports filed this week"** was not this week. `week_ago` is measured
      back from `MAX(filed_at)`, so a database that has not been touched in a
      month still reports a full week's work. The window claim goes; the count
      is real and stays.
    """
    median = int(stats.get("median_detect_to_file_seconds", 0))
    if median >= 3600:
        latency, unit = f"{median // 3600}", "h"
    elif median >= 60:
        latency, unit = f"{median // 60}", "m"
    else:
        latency, unit = f"{median}", "s"

    return [
        {
            "value": f"{stats.get('filed_this_week', 0)}",
            "unit": "",
            "label": "reports filed",
        },
        {
            "value": f"{stats.get('missed_by_feed_pct', 0)}",
            "unit": "%",
            "label": "cleared the gate, not a duplicate",
        },
        {"value": latency, "unit": unit, "label": "median spot → filed"},
        {
            "value": f"{stats.get('open_cases', 0)}",
            "unit": "",
            "label": "still being chased",
        },
    ]


def state_label(code: str) -> str:
    return STATE_LABELS.get(code, code)


# ------------------------------------------------------------------- incidents


def incident_row(incident: Incident) -> dict[str, Any]:
    """One saved dashcam finding, as the incidents page renders it.

    The image is addressed by route rather than by blob key. The key is a
    storage detail that changes when a deployment moves between local disk and
    GCS, and it is also the one string that must not be client-controllable --
    `/api/incidents/{id}/image` resolves it server-side from a record fetched
    under the caller's own uid.
    """
    hazard_key = incident.hazard_type.value
    return {
        "id": incident.id,
        "hazard": HAZARD_LABELS.get(hazard_key, hazard_key.replace("_", " ").title()),
        "hazard_key": hazard_key,
        "severity": incident.severity.value,
        "confidence": round(incident.confidence, 2),
        "description": incident.description,
        "when": when(incident.created_at),
        "at": incident.created_at.isoformat(),
        "location": incident.location,
        "state": incident.state,
        "lat": incident.lat,
        "lng": incident.lng,
        "agency": incident.agency_name,
        "agency_email": incident.agency_email,
        "agency_endpoint": incident.agency_endpoint,
        "channel": CHANNEL_LABELS.get(
            incident.channel.value if incident.channel else "", ""
        ),
        "subject": incident.report_subject,
        "body": incident.report_body,
        "image_url": f"/api/incidents/{incident.id}/image" if incident.image_keys else None,
        "box": incident.box.model_dump() if incident.box else None,
        "box_measured": incident.box_is_measured,
        "box_label": incident.hazard_label,
        "emailed_to": incident.emailed_to,
        # Three distinguishable states, not two. "Not sent" and "tried and
        # refused" are different facts, and the second one is the interesting
        # one -- it usually means DASHCAM_NOTIFY_DOT is on and the address is
        # not allowlisted, which is a configuration answer, not a bug.
        "dot_state": (
            "sent" if incident.dot_notified else ("refused" if incident.dot_error else "held")
        ),
        "dot_destination": incident.dot_destination,
        "dot_error": incident.dot_error,
        "model": incident.model_name,
    }
