"""Provenance sidecars for generated media.

Every generated artifact is written with a `.json` sidecar recording which model
made it, from what prompt, and which detection seeded it.

The alternative -- reading the model name back out of the filename -- looked fine
until a Chirp briefing came out badged "generated by briefing". Provenance that
is inferred is provenance that can be wrong, and being able to say exactly what
produced a clip is the entire basis for showing it next to real evidence.

Sidecars sit in the media store beside the file, never in the case repository:
synthetic media is deliberately not part of the audit trail.
"""

from __future__ import annotations

from pathlib import PurePosixPath

from road_cleaner.logging import get_logger
from road_cleaner.ports.blob_store import BlobNotFoundError, BlobStore
from road_cleaner.ports.media import SyntheticClip

log = get_logger(__name__)

MANIFEST_SUFFIX = ".json"


def manifest_key(media_key: str) -> str:
    return f"{media_key}{MANIFEST_SUFFIX}"


async def write_manifest(store: BlobStore, clip: SyntheticClip) -> None:
    """Persist a clip's provenance next to it.

    Failure to write the sidecar is logged, not raised: the clip itself already
    exists and is already labelled synthetic by its key prefix, so losing the
    manifest degrades the caption rather than the guarantee.
    """
    try:
        await store.put(
            manifest_key(clip.key),
            clip.model_dump_json(indent=2).encode("utf-8"),
            content_type="application/json",
        )
    except Exception as exc:  # noqa: BLE001 - never fail a render over a caption
        log.warning(
            "Could not write provenance sidecar",
            extra={"key": clip.key, "error": str(exc)},
        )


async def prune_superseded(store: BlobStore, keep_key: str, prefix: str) -> int:
    """Delete earlier generated media under `prefix`, keeping only `keep_key`.

    Re-rendering a scenario replaces the old clip rather than stacking another
    20MB beside it. Old clips are worth nothing once a better one exists -- they
    are regenerable by definition, which is exactly what evidence frames are not.
    That asymmetry is why this lives here and nothing like it touches
    `data/frames/`.

    Only media of the *same kind* is pruned, matched on file extension. A case
    folder holds the clip and the spoken briefing side by side, and rendering a
    new video must not delete the audio that has nothing to do with it.

    Sidecars are removed with the clips they describe, and a failure to prune is
    logged rather than raised: the new clip is already safely written, and losing
    disk space is a smaller problem than losing the render.
    """
    keep = {keep_key, manifest_key(keep_key)}
    suffix = PurePosixPath(keep_key).suffix.lower()
    removed = 0
    try:
        for key in await store.list_keys(prefix):
            if key in keep:
                continue
            # Sidecars are judged by what they describe, not by their own ".json".
            described = key[: -len(MANIFEST_SUFFIX)] if key.endswith(MANIFEST_SUFFIX) else key
            if PurePosixPath(described).suffix.lower() != suffix:
                continue
            await store.delete(key)
            removed += 1
    except Exception as exc:  # noqa: BLE001 - never fail a render over cleanup
        log.warning("Could not prune superseded media", extra={"error": str(exc)})
        return removed
    if removed:
        log.info("Pruned superseded media", extra={"prefix": prefix, "removed": removed})
    return removed


async def read_manifest(store: BlobStore, media_key: str) -> SyntheticClip | None:
    """Load a clip's provenance, or None if it was never written."""
    try:
        raw = await store.get(manifest_key(media_key))
    except (BlobNotFoundError, ValueError):
        return None
    try:
        return SyntheticClip.model_validate_json(raw)
    except ValueError:
        return None
