"""Decoding a clip into the stills the analyst reads.

The failure that matters here is silent: if the seek snaps to the nearest
keyframe, every sample comes back as the same picture, the analysis "agrees"
across all five frames, and the page reports high confidence in a hazard it
looked at exactly once. So the tests decode a real file and assert the frames
actually differ, rather than mocking ffmpeg and proving only that the arguments
were spelled correctly.

The fixture clip is generated by ffmpeg itself, so these tests depend on nothing
in `data/`.
"""

from __future__ import annotations

import asyncio
import hashlib
import subprocess
from pathlib import Path

import pytest

from road_cleaner.adapters.media.frame_extract import (
    EDGE_INSET_SECONDS,
    FrameExtractionError,
    SampledFrame,
    ffmpeg_path,
    probe_duration,
    sample_clip,
    sample_times,
)

CLIP_SECONDS = 4


@pytest.fixture(scope="module")
def clip(tmp_path_factory) -> Path:
    """A 4-second clip whose every frame is visibly different from the last.

    `testsrc` draws a running frame counter, which is what makes "did the seek
    actually move" an observable property rather than an assumption.
    """
    path = tmp_path_factory.mktemp("clips") / "test.mp4"
    subprocess.run(
        [
            ffmpeg_path(), "-y", "-loglevel", "error",
            "-f", "lavfi", "-i", f"testsrc=duration={CLIP_SECONDS}:size=320x180:rate=24",
            "-pix_fmt", "yuv420p", str(path),
        ],
        check=True,
        capture_output=True,
    )
    return path


def _signature(jpeg: bytes) -> str:
    return hashlib.md5(jpeg).hexdigest()


class TestSampleTimes:
    """Pure arithmetic, so tested without touching a file."""

    def test_samples_are_spread_across_the_clip_and_inset_from_both_ends(self):
        times = sample_times(8.0, 5)
        assert times == [0.4, 2.2, 4.0, 5.8, 7.6]
        assert times[0] >= EDGE_INSET_SECONDS
        assert times[-1] <= 8.0 - EDGE_INSET_SECONDS

    def test_every_sample_lands_inside_the_clip(self):
        for duration in (0.5, 1.0, 8.0, 30.0):
            for count in (1, 2, 5, 12):
                assert all(0 <= t <= duration for t in sample_times(duration, count))

    def test_a_clip_shorter_than_the_inset_still_yields_one_frame(self):
        """0.3s of footage is degenerate, but returning nothing loses the clip."""
        assert sample_times(0.3, 5) == [0.15]

    def test_asking_for_no_frames_returns_none(self):
        assert sample_times(8.0, 0) == []

    def test_the_samples_are_in_order(self):
        times = sample_times(8.0, 7)
        assert times == sorted(times)


class TestDecoding:
    async def test_duration_is_read_from_the_file(self, clip):
        assert await probe_duration(clip) == pytest.approx(CLIP_SECONDS, abs=0.2)

    async def test_every_sample_is_a_different_moment(self, clip):
        """The keyframe-snap bug: five samples, one actual picture.

        If this regresses, the analysis silently corroborates itself.
        """
        frames = await sample_clip(clip, 5)
        assert len(frames) == 5
        assert len({_signature(f.jpeg) for f in frames}) == 5

    async def test_frames_are_jpeg_and_carry_their_timestamp(self, clip):
        frames = await sample_clip(clip, 3)
        for i, frame in enumerate(frames):
            assert isinstance(frame, SampledFrame)
            assert frame.jpeg.startswith(b"\xff\xd8"), "not a JPEG"
            assert frame.index == i
            assert 0 <= frame.at_seconds <= CLIP_SECONDS
        assert [f.at_seconds for f in frames] == sorted(f.at_seconds for f in frames)

    async def test_the_stamp_is_what_the_ui_shows(self, clip):
        assert SampledFrame(index=0, at_seconds=3.24, jpeg=b"").stamp == "3.2s"

    async def test_samples_are_decoded_concurrently(self, clip):
        """Serially this is the slowest step on the page, for no reason."""
        import time

        start = time.monotonic()
        await sample_clip(clip, 5)
        together = time.monotonic() - start

        start = time.monotonic()
        for t in sample_times(CLIP_SECONDS, 5):
            await asyncio.sleep(0)
            from road_cleaner.adapters.media.frame_extract import extract_frame

            await extract_frame(clip, t)
        serial = time.monotonic() - start

        assert together < serial, "sample_clip is no faster than doing it one at a time"


class TestBrokenInputSaysSo:
    """A decode failure must never look like 'the road was clear'."""

    async def test_a_missing_file_raises(self, tmp_path):
        with pytest.raises(FrameExtractionError, match="No clip at"):
            await sample_clip(tmp_path / "nope.mp4")

    async def test_a_file_that_is_not_a_video_raises(self, tmp_path):
        junk = tmp_path / "junk.mp4"
        junk.write_bytes(b"this is not an mp4")
        with pytest.raises(FrameExtractionError):
            await sample_clip(junk)

    async def test_seeking_past_the_end_raises_rather_than_returning_empty(self, clip):
        from road_cleaner.adapters.media.frame_extract import extract_frame

        with pytest.raises(FrameExtractionError, match="No frame at"):
            await extract_frame(clip, CLIP_SECONDS + 30)
